### ISSUE TITLE
Charge limit does not work because of no automatic refresh

### ISSUE THREAD

**Issue by Machabi82** [andreadegiovine/homeassistant-stellantis-vehicles#24]
### Mark

Opel

### Model

Mokka e

### Year

2021

### Engine

Electric

### What happened?

The values (Milage, SoC, etc...) only updates when I press "wake up". They update not automatic. Because of that I think the charge limit does not work, What could be the reason?

Thanks and kind regards,
Mario

### Log output

```shell

```

**Comment by andreadegiovine** [comment]
@Machabi82 i have the same issue 😒 idem from MyOpel app.
I think the problem is on the car, 1 year ago the data was update regularly, but in the last year i need to wakeup to get uodates.

When you start the engine appear on the main display a notice about “Power saving mode”?

What service battery level you have?

Can you paste here the log contain the vehicle status (hide coordinates)?

On my HA i use 2 automations:
- every 5mins if charging binary sensor is “on” click on wakeup
- every 1hour if charging binary sensor is “off” click wakeup

**Comment by Machabi82** [comment]
When you start the engine appear on the main display a notice about “Power saving mode”?
_No_

What service battery level you have?
_89%_

Can you paste here the log contain the vehicle status (hide coordinates)?
_Will try to get the log tomorrow_

On my HA i use 2 automations:
every 5mins if charging binary sensor is “on” click on wakeup
every 1hour if charging binary sensor is “off” click wakeup

good idea, if no other solution

**Comment by Machabi82** [comment]
Good Morning,

Could you please help with the automations


  *   every 5mins if charging binary sensor is “on” click on wakeup
  *   every 1hour if charging binary sensor is “off” click wakeup

And copy/paste me the code? Could not get it working...

Thanks, Mario

________________________________
Von: andreadegiovine ***@***.***>
Gesendet: Donnerstag, Februar 13, 2025 10:15 PM
An: andreadegiovine/homeassistant-stellantis-vehicles ***@***.***>
Cc: Mario Engels ***@***.***>; Mention ***@***.***>
Betreff: Re: [andreadegiovine/homeassistant-stellantis-vehicles] Charge limit does not work because of no automatic refresh (Issue #24)

Sie erhalten nicht häufig E-Mails von ***@***.*** Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Externe Mail!

Closed #24<https://github.com/andreadegiovine/homeassistant-stellantis-vehicles/issues/24> as completed.

**Comment by andreadegiovine** [comment]
> Good Morning,
> 
> Could you please help with the automations
> 
> 
>   *   every 5mins if charging binary sensor is “on” click on wakeup
>   *   every 1hour if charging binary sensor is “off” click wakeup
> 
> And copy/paste me the code? Could not get it working...
> 
> Thanks, Mario
> […](#)

Every 5 min:
```
- id: "mokka_wakeup"
  alias: Mokka - Svegliati (non in carica)
  description: ""
  mode: single
  triggers:
    - trigger: time_pattern
      hours: /1
  conditions:
    - condition: state
      entity_id: binary_sensor.VIN_batteria_in_ricarica
      state: "off"
  actions:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.VIN_svegliati
```

Every hour:
```
- id: "mokka_wakeup_charging"
  alias: Mokka - Svegliati (in carica)
  description: ""
  mode: single
  triggers:
    - trigger: time_pattern
      minutes: /5
  conditions:
    - condition: state
      entity_id: binary_sensor.VIN_batteria_in_ricarica
      state: "on"
  actions:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.VIN_svegliati
```
