### ISSUE TITLE
Keyless entry stopped working

### ISSUE THREAD

**Issue by FrankTub** [andreadegiovine/homeassistant-stellantis-vehicles#48]
### Mark

Citroen

### Model

E-C4

### Year

2022

### Engine

Electric

### Remote service

E-remote

### What happened?

Not 100% sure that it is related to using this repository but I have a Citroen E-C4 with keyless entry. This has stopped working relatively quickly after I started using this repository. I called the dealer and they replaced the battery of both my keys and the issue persists.

The issue is also reported on many other [threads](https://www.speakev.com/threads/remote-locking-and-keyless-entry-failing-on-e208.179423/), I experience exactly the same behavior now:

> I'm getting a strange behaviour with our e208. If the car has been sitting for more than 10-15 mins then the keyless entry and remote unlocking doesn't work. If I use the physical key to enter and start the car then turn it off, the fobs start working normally and if I drive to my destination locking and unlocking are fine. However if it sits again for long enough then it stops working again

I've setup an automation to call wakeup and my thought was that it was worth reporting back to you since I guess it could cause the 12V battery in the car to drop charge or anything?

My current automation I have setup to call wakeup:

```yml
- id: '1739801562568'
  alias: Wakeup Citroen
  description: Minimaal iedere 3 uur Citroen wakeup request sturen zodat Citroen in ieder
    geval zijn status door blijft geven. In het geval dat hij aan het laden is passen
    we dit aan naar iedere 5 minuten
  triggers:
  - trigger: time_pattern
    hours: /3
    id: every-3-hours
  - trigger: time_pattern
    minutes: /5
    id: every-5-minutes
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - every-3-hours
    - condition: numeric_state
      entity_id: sensor.<VIN>_batterij_laad_snelheid
      below: 1
    then:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.<VIN>_wakker_worden
  - if:
    - condition: trigger
      id:
      - every-5-minutes
    - condition: numeric_state
      entity_id: sensor.<VIN>_batterij_laad_snelheid
      above: 1
    then:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.<VIN>_wakker_worden
  mode: single
```

The first time I started experiencing the issue was after I left my car connected to my charger and had the automation still setup in such a way that even when no charge was added, but the charger was connected it still refreshed the state of the car every 3 minutes for a day or something. Perhaps this has drained the battery that is also used to unlock the car?

Not sure if you can do anything about it, but thought it was worth mentioning in this repo.

### Log output

```shell

```
