### ISSUE TITLE
Commands sent to the car keeps failing

### ISSUE THREAD

**Issue by FrankTub** [andreadegiovine/homeassistant-stellantis-vehicles#73]
### Mark

Citroen

### Model

E-C4

### Year

2022

### Engine

Electric

### Remote service

E-remote

### What happened?

On older versions than `0.3.14` the wakeup command was working fine, however I'm currently in the situation where wakeup has stopped working again. Other commands like pre-conditioning also seem to fail. Any idea what is changed that this behavior popped up again?

Perhaps it has something to do with that the device in HA is updated every minute while the car is connected to the charger, even if it's not charging?

<img width="329" alt="Image" src="https://github.com/user-attachments/assets/1fc62f57-8fed-427e-b07b-036b3f34c40f" />

In HA I see that the car state is charging:

<img width="360" alt="Image" src="https://github.com/user-attachments/assets/1ec67024-ea50-4bc1-889d-4a8e644bbe89" />

But my charger is sure not to charge when there is no extra solar panel production, so above screenshot is made when the car has not been charging for at least 2 hours.

<img width="560" alt="Image" src="https://github.com/user-attachments/assets/c0cab4fc-515b-4d96-a525-8dd894b5f92f" />

The command history:

<img width="583" alt="Image" src="https://github.com/user-attachments/assets/2ae22932-f113-4c40-9990-fe1818e62e86" />

### Log output

```shell

```

**Comment by Mike-cpu404** [comment]
@FrankTub Can you post up your log so that we can see what the error is?

**Comment by FrankTub** [comment]
@Mike-cpu404 , I went through the logging but I did not seem to find any events in the home assistant log related to this issue.

**Comment by andreadegiovine** [comment]
@FrankTub sorry but i cant undestand the sensors name from screenshot :D

From the homeassistant.log file (if the debug level is configurel like main page of this integration) you can find any info about sensors and commands.

In my case, sometimes the command fail (Error in history) because the vehicle e-sim signal is very low (in garage, tunnel, ecc)

**Comment by FrankTub** [comment]
It happens when the car is also not reachable via the MyCitroen app. In the app it displays. Where the message shows you in dutch that you should at least use your car for 15 minutes uninterupted, the last time I did that was on Friday evening, so it is not a really smart message. The other option they provide is indeed when the vehicle e-sim signal is very low. But this can't be the case because I have it in front of my house where it has worked more often than not and we good mobile coverage in this region.

![Image](https://github.com/user-attachments/assets/cde880f2-bb17-42d2-acd1-3fc5d3add3e2)

Just guessing, but could it be that it has something to do with the battery level of my 12V accu?

![Image](https://github.com/user-attachments/assets/cbd412a9-06ea-4d8c-a238-aaa90f7b1569)

Note: I do have any automation going on to call the wakeup command, but these dips in the charge seem unrelated to the wakeup command. So not sure why my 12V accu is losing so much battery, but it could be that something in this integration is changed to call the car more often?

My automation currently looks like:

```yaml
- id: '1739801562568'
  alias: Wakeup Citroen
  description: Minimaal iedere 6 uur Citroen wakeup request sturen zodat Citroen in
    ieder geval zijn status door blijft geven.
  triggers:
  - trigger: time_pattern
    hours: /6
    id: every-6-hours
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - every-6-hours
    - condition: numeric_state
      entity_id: sensor.vr7bczkxcne008910_batterij_laad_snelheid
      below: 1
    then:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.vr7bczkxcne008910_wakker_worden
  mode: single
```

Might be unrelated but perhaps the wakeup in combination with a driving car is giving those symptoms?
